### ISSUE TITLE
Nimsuggest crashes when run without a backend specified

### ISSUE THREAD

**Issue by liquidev** [nim-lang/nimsuggest#117]
Happens on [this file](https://github.com/liquid600pgm/rapid/blob/1a819aafa4424177da127de1b42dc4a0b705f57d/tests/tchipmunk.nim), I haven't been able to reproduce it on a smaller example but that shouldn't matter.

Since Nim 1.4 nimsuggest hits an assertion when run like this:
```
❯ nimsuggest tests/tchipmunk.nim
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/config.nims' [Conf]
Hint: used config file '/home/daknus/.config/nim/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.config/nim/config.nims' [Conf]
Hint: used config file '/home/daknus/Coding/Nim/rapid/tests/config.nims' [Conf]
fatal.nim(49)            sysFatal
Error: unhandled exception: extccomp.nim(631, 31) `false`  [AssertionDefect]
```

It doesn't crash however when the backend is specified explicitly:
```
❯ nimsuggest -b:c tests/tchipmunk.nim
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/config.nims' [Conf]
Hint: used config file '/home/daknus/.config/nim/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.config/nim/config.nims' [Conf]
Hint: used config file '/home/daknus/Coding/Nim/rapid/tests/config.nims' [Conf]
usage: sug|con|def|use|dus|chk|mod|highlight|outline|known|project file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> 
```
And also doesn't crash on Nim 1.2.6.

My hunch is that the compiler itself initializes the backend to C by default, but not nimsuggest, hence the assertion is hit because the default backend is `backendInvalid`.

**Comment by timotheecour** [comment]
@liquid600pgm can you try right before this commit https://github.com/nim-lang/Nim/pull/15549 as mentioned here: 
https://github.com/nim-lang/Nim/pull/15602#issuecomment-711419933

**Comment by liquidev** [comment]
As per @Clyybber's suggestion on Discord, I cleared the nimcache and everything works correctly so far. I'll reopen if this ever turns up again.

**Comment by timotheecour** [comment]
having to clear the cache might be an acceptable-ish solution if using 2 different versions of nim, but not if using same version of nim and running some commands; is there a repro?

**Comment by liquidev** [comment]
I was able to reproduce this using the following steps:
```sh
# before running anything we're on 1.4.0, in rapid's root folder
choosenim 1.2.6
nim c tests/tchipmunk
choosenim 1.4.0
nimsuggest tests/tchipmunk.nim
```

**Comment by timotheecour** [comment]
thanks for the repro, I still think we should fix this

**Comment by liquidev** [comment]
Seems to still be present, and quite annoying :/ reopening.

It can just crash in the middle of editing the file (using [nim.nvim](https://github.com/alaviss/nim.nvim)) which then forces me to stop writing code, switch to my terminal, `rm -rf ~/.cache/nim`, and restart nimsuggest via a custom command. And it makes compile times slower because the cache is now gone.

**Comment by timotheecour** [comment]
can you try https://github.com/nim-lang/nimsuggest/issues/117#issuecomment-711420582 ?
