### ISSUE TITLE
nimsuggest outline doesn't account for includes

### ISSUE THREAD

**Issue by saem** [nim-lang/nimsuggest#119]
# What's busted

When outline is called on a file with includes, nimsuggest doesn't not show included procs, vars, etc... One could ask the same about template and macro expansion, but the key differences are:
* an include pulls in the AST derived from some concrete syntax that is resident in the file system/source tree
* an included item shown in an outline has a concrete location where the user can be taken to when resolving it to a location in the source tree

[see the outline part of the test case for expected results.](https://github.com/nim-lang/Nim/compare/devel...saem:saem-nimsuggest-handle-includes-in-outline?expand=1)

# How it should work

`outline` should therefore return symbols that have been included from elsewhere. How clients of nimsuggest would use this:
1. when showing an outline they can simply show all items as is
1. when showing an outline but they wish to restrict it to only current file they can filter the results based on file name (they know the open file)
1. when determining if something is from an include, it's the same as above, if it doesn't match the file it's an include

## How the fix isn't a breaking change
One might suggest (hah!) that this is a breaking change, it is not:
* technically speaking nimsuggest does not document/describe the outline interface, merely its existence, you can't break a promise you don't make
* the spirit of outline is preserved and strengthened: show an AST/semantic outline of a module (not file, which merely serves as an identifier/disambiguator)
* IDEs/editors showing a view will still be able to do so:
  * ones that are unaware will show a few extra symbols but those are definitely there in the module -- truthy!
  * ones that are aware of this change can provide a further option to filter or pre-filter if they wish to keep up the lie ;)
  * ones that provide a goto functionality should be using the file path returned anyways and they gain easy functionality
  * ones that are aware and make use of it, but simply don't get the results because of an old nim/nimsuggest will gracefully fallback

# What's the fix?

Still not entirely sure, but I suspect that `suggest.markUsed` could use the `PContext` parameter's various scope fields to determine if this is an include and add propogate that information through `suggest.suggestSym`, `symToSuggest`, etc...

**Comment by Araq** [comment]
IMHO the outline feature should simply be removed altogether. I don't like "semantic" source code highlighting at all.

**Comment by saem** [comment]
@Araq how would we go about providing tree views and explorers?

For refactoring tools, such as rename, which needs to have just enough semantics information to know that these two symbols are equivalent, but not too much such that it's possible to reason across conditional compilation branches or modules across packages within some sort of concept of solution (think mono repo), I think we're going to need these sorts of analyses and facilities. To either provide them within or expose enough information to provide them without.

**Comment by Araq** [comment]
These tools all should be based on the .rod file mechanism. It's still in development, help is appreciated. The progress is fine though.
