### ISSUE TITLE
Follow symlinks when looking for the stdlib

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/nimsuggest#12]
See https://github.com/nim-lang/nimsuggest/issues/6#issuecomment-116249767

**Comment by Araq** [comment]
We already have ``--lib`` and some other shit for this. Lot's of questions come to mind:

* How many switches do we need for this?
* Why cannot ``nimsuggest`` be next to ``nim`` in the first place?
* Why does Andrew Ryan not use his Vita Chamber?

**Comment by reactormonk** [comment]
No more switches. And since nimsuggest is installed via nimble, having them in the same dir is not always possible.

**Comment by Araq** [comment]
I think the compiler now follows symlinks.
