### ISSUE TITLE
compiler hints causing EPC protocol errors

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/nimsuggest#13]
On some installations `nimsuggest` outputs Hints before outputting port:

```
config/nim.cfg(53, 3) Hint: added path: '/home/michal/.babel/pkgs/' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/michal/.nimble/pkgs/compiler-0.11.3' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/michal/.nimble/pkgs/nimble-0.6.2' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/michal/.nimble/pkgs/c2nim-0.9.8' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/michal/.nimble/pkgs/nimenv-0.0.1' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/michal/.nimble/pkgs/nimsuggest-0.1.0' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/michal/.nimble/pkgs/docopt-0.6.1' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/michal/.nimble/pkgs/' [Path]
Hint: used config file '/home/michal/apps/nim/config/nim.cfg' [Conf]
30005
```
This causes emacs-side EPC to think that something went wrong and abort session. Invoking nimsuggest with '--hint[Conf]=off' '--hint[Path]=off' args fixes this issue.

The issue seems to be related to 8f65981c439f0270f7c9dc23c1f36b26f0256b01, but I couldn't find compiler/nimsuggest versions on which this issue is absent.

**Comment by reactormonk** [comment]
Yeah, gotta reorder the next free port and the print earlier again :-/

**Comment by reactormonk** [comment]
I don't exactly know where these hints come from, could you place markers (e.g. `echo "foo"`) in the nimsuggest code and see which line they come from?

**Comment by zielmicha** [comment]
These messages come from `loadConfigs`. Workaround like this is possible:

```patch
diff --git a/nimsuggest.nim b/nimsuggest.nim
index 500fae3..cf3c05f 100644
--- a/nimsuggest.nim
+++ b/nimsuggest.nim
@@ -337,7 +337,10 @@ proc handleCmdLine() =
           "Cannot find Nim standard library: Nim compiler not in PATH")
     gPrefixDir = binaryPath.splitPath().head.parentDir()
 
+    let originalOptions = gOptions
+    gOptions = gOptions - {optHints}
     loadConfigs(DefaultConfig) # load all config files
+    gOptions = originalOptions
     # now process command line arguments again, because some options in the
     # command line can overwite the config file's settings
     extccomp.initVars()
```

**Comment by reactormonk** [comment]
I think the proper solution is using `connectToNextFreePort` and printing the port before `loadConfigs` and pass the socket around - the OS can do the buffering for us until we're ready.

**Comment by pigmej** [comment]
@reactormonk not quite, we have 3 seconds to print and accept connection on port. Which might be not the case sometimes.

I experimented with temporary disabling output (dup to other fd), and then restoring it. But I don't remember state of it right now ;/

**Comment by reactormonk** [comment]
@pigmej ah fuck. So WA with disabling output and then get yours going?

**Comment by yuutayamada** [comment]
I'm closing this issue because now nimsuggest for epc sets --verbosity:0 when
it uses suggest options (sug, con, def, use, and dus).
Please re-open or make new issue if you still have this issue.
