### ISSUE TITLE
Fails to start on windows 11

### ISSUE THREAD

**Issue by creikey** [nim-lang/nimsuggest#131]
Steps to reproduce:

1. completely reinstall your computer with a fresh install of windows 11
2. download choosenim, use nim 1.6.6
3. install, then run `nimsuggest.exe` on command line

This is the result:
![image](https://user-images.githubusercontent.com/28424206/179340786-a402fd87-525c-425e-9f73-c22e2c540197.png)

**Comment by ringabout** [comment]
Hi @creikey is it related to libwinthread.dll?

**Comment by ringabout** [comment]
Duplicate of https://github.com/nim-lang/Nim/issues/19713
