### ISSUE TITLE
Cannot install via nimble

### ISSUE THREAD

**Issue by kFo** [nim-lang/nimsuggest#14]
$ nimble install nimsuggest
Downloading https://github.com/nim-lang/nimsuggest.git into C:\Users\efool\AppData\Local\Temp\nimble_4992\githubcom_nimlangnimsuggestgit using git...
Cloning into 'C:\Users\efool\AppData\Local\Temp\nimble_4992\githubcom_nimlangnimsuggestgit'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Checking connectivity... done.
Looking for compiler (>= 0.11.3)...
None found, installing...
Downloading https://github.com/Araq/Nim.git into C:\Users\efool\AppData\Local\Temp\nimble_4992\githubcom_AraqNimgit_0.11.3 using git...
Found tags...
Cloning latest tagged version:
Cloning into 'C:\Users\efool\AppData\Local\Temp\nimble_4992\githubcom_AraqNimgit_0.11.3'...
remote: Counting objects: 1928, done.
remote: Compressing objects: 100% (1823/1823), done.
remote: Total 1928 (delta 46), reused 852 (delta 37), pack-reused 0
Receiving objects: 100% (1928/1928), 3.21 MiB | 2.85 MiB/s, done.
Resolving deltas: 100% (46/46), done.
Checking connectivity... done.
Unsatisfied dependency: nim (>= 0.11.3)

$ nim --version
Nim Compiler Version 0.11.2 (2015-10-02) [Windows: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 8dedfdb236cc50a811ec3423de492368d4ed6329
active boot switches: -d:release

$ nimble --version
nimble v0.6.2 compiled at 2015-10-02 22:48:22

**Comment by dom96** [comment]
After that change, make sure you have the devel compiler installed, otherwise it won't compile.
