### ISSUE TITLE
nimsuggest, position for column is of by one.

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/nimsuggest#30]
$ cat t.nim 
echo "test"

nimsuggest --stdin t.nim
def t.nim:1:1
def skProc  system.echo proc (x: varargs[typed]){.gcsafe, locks: 0.}    /home/stefan/Nim/lib/system.nim 2482    7   ""

$ cat /home/stefan/Nim/lib/system.nim | grep "proc echo" 
  proc echo*(x

From docs line and column position starts at 1 each, so position should be 2482  8! (there are 7 characters in from of echo, if you substract these, you would get position zero currently. So we should fix documentation or code, otherwise it is confusing. More serious bugs may follow...

**Comment by StefanSalewski** [comment]
Note: Comment in source code is correct, only documentation is wrong.
http://nim-lang.org/docs/nimsuggest.html
For the compiler columns start at 1.

docstring = sexp("line starts at 1, column at 0, dirtyfile is optional")

**Comment by Araq** [comment]
The docs now say columns start at 0. Which is true.
