### ISSUE TITLE
chk system.nim:1:0 works fine, but def not

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/nimsuggest#34]
Did one more test to see if nimsuggest can compile system.nim at all -- and it can, chk command works fine:

nimsuggest --stdin system.nim
debug
chk system.nim:1:0
only some warnings
But when I try to query the len proc:
def system.nim:2136:5
lib/system.nim(163, 17) Warning: expr is deprecated [Deprecated]
lib/system.nim(2136, 19) Error: type mismatch: got (openarray[T])
but expected one of: 
proc len[T](x: seq[T]): int
proc len[I, T](x: array[I, T]): int
proc len(x: cstring): int
proc len(x: string): int
proc len[TOpenArray: openArray | varargs](x: TOpenArray): int

lib/system.nim(2136, 9) Error: type mismatch: got (void, )
but expected one of: 
proc newSeq[T](s: var seq[T]; len: Natural)
proc newSeq[T](len = 0.Natural): seq[T]

lib/system.nim(2137, 16) Error: type mismatch: got (openarray[T])
but expected one of: 
proc len[T](x: seq[T]): int
proc len[I, T](x: array[I, T]): int
proc len(x: cstring): int
proc len(x: string): int
proc len[TOpenArray: openArray | varargs](x: TOpenArray): int

lib/system.nim(2137, 24) Error: expression 'result' has no type (or is ambiguous)
lib/system.nim(2137, 30) Error: type mismatch: got ()
but expected one of: 
proc `[]=`[I: Ordinal, T, S](a: T; i: I; x: S)

lib/system.nim(2218, 74) Warning: expr is deprecated [Deprecated]

**Comment by Araq** [comment]
Can you give the context for ``def system.nim:2136:5``. This bug report is tied to a specific system version.

**Comment by StefanSalewski** [comment]
system.nim:2136:5 is line with "newseq" from

proc `@`*[T](a: openArray[T]): seq[T] =
  ## turns an openarray into a sequence. This is not as efficient as turning
  ## a fixed length array into a sequence as it always copies every element
  ## of `a`.
  newSeq(result, a.len)
  for i in 0..a.len-1: result[i] = a[i]
