### ISSUE TITLE
Summary of the system.nim bug

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/nimsuggest#35]
As you may have missed that summary on IRC:
(I have very good nimsuggest support for my GTK editor now, including use support with replacing symbols in current module, and permanent def support, which displays info for symbols when cursor moves to that symbols. Done with own process and channel communication.)

The strange thing is, that compiling gives errors for the requested line range. For example def system.nim;system.nim:2136:5 results in errors for lines 2137 and 2138

Maybe that is easy for you -- I have no idea. I can not imagine why compiler is influenced by the requested line range.

And the logic for --v2 option and missing dirtyfile is wrong, for that combination we get generally no output.

I have tried also compiling nimsuggest as nim e compile_without_nimble nimsuggest.nim -- make no difference.

**Comment by Araq** [comment]
> And the logic for --v2 option and missing dirtyfile is wrong, for that combination we get generally no output.

This has been fixed.
