### ISSUE TITLE
Tag versions whenever a stable version of Nim is published

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimsuggest#36]
So that people using - say - 0.14.2 are able to use the corresponding version of nimsuggest

**Comment by andreaferretti** [comment]
Please, could you add the tag `0.15.0`, both in the `.nimble` file and as a git tag?

The problem I am trying to solve is the following: unlike other libraries, nimsuggest is strictly tied to particular versions of the compiler. When switching compiler versions - for instance using [nimvm](https://github.com/ekarlso/nim-vm) - autocompletion will break and even crash, making nimsuggest unusable other than on devel.

If the project was tagged, it would be easy to jump between nimsuggest versions when changing compiler version. It is a step that takes only a few seconds, but it is a great aid in usability of the whole ecosystem.

**Comment by Araq** [comment]
0.15.2 was tagged, but nimsuggest is now part of the Nim core again. Compiler API changes are about to come.
