### ISSUE TITLE
Two more issues

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/nimsuggest#38]
use command ignores proc parameters. Maybe that is intended?

And export marker makes a difference for def command. Maybe also intended?
Here is the input test file:
type
  T = RootObj
  TTT1 = object of T
    iii: int

  TTT2\* = object of T
    iii*: int

proc max(xxx, yyy: int): int =
  if xxx > yyy: xxx else: yyy

And shell output:
$ nimsuggest --v2 --stdin t.nim 

> def t.nim;t.nim:3:4
> def skType  t.TTT1      /home/stefan/sugt/t.nim 3   2   ""  100
> 
> def t.nim;t.nim:4:5
> def skField t.TTT1.iii      /home/stefan/sugt/t.nim 4   4   ""  100
> 
> def t.nim;t.nim:6:4
> 
> def t.nim;t.nim:7:4
> 
> use t.nim;t.nim:10:7
> use skParam t.max.xxx   int /home/stefan/sugt/t.nim 10  5   ""  100
> use skParam t.max.xxx   int /home/stefan/sugt/t.nim 10  16  ""  100
> 
> quit

**Comment by timotheecour** [comment]
@StefanSalewski I suggest changing title name or creating 1 issue per bug

**Comment by timotheecour** [comment]
/cc @StefanSalewski 
same as https://github.com/nim-lang/nimsuggest/issues/64#issuecomment-435481945 ; it's usually good practice to write a comment when closing an issue to indicate why it was closed (was it resolved? etc)
