### ISSUE TITLE
Cannot open standard imports

### ISSUE THREAD

**Issue by BitR** [nim-lang/nimsuggest#4]
Reproduced this bug in a clean docker instance, based on ubuntu.
After having done the following I get this error: "Error: cannot open '/root/.nimble/pkgs/lib/system.nim'"
* Bootstrap and install Nim
* Build and install latest nimble version
* nimble install nimsuggest

See this [Dockerfile](https://gist.github.com/BitR/1ab859b62fd79d1c40a4) for the setup.

Full error:

    docker run --rm -it nimsuggest nimsuggest /nim/lib/pure/complex.nim

        /etc/nim.cfg(53, 3) Hint: added path: '/root/.babel/pkgs/' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/compiler-0.11.3' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimble-0.6.0' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimsuggest-0.1.0' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/' [Path]
        Hint: used config file '/etc/nim.cfg' [Conf]
        Error: cannot open '/root/.nimble/pkgs/lib/system.nim'
        math.nim(16, 9) Error: cannot open 'system/inclrtl'
        SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by reactormonk** [comment]
I fixed the `cannot open` problem by updating both compiler and nimsuggest. Also, move nimsuggest to the compiler directory.

**Comment by BitR** [comment]
After updating the Dockerfile to copy nimsuggest to /usr/bin alongside the nim binary, I get this output:

    docker run --rm -it nimsuggest nimsuggest /nim/lib/pure/complex.nim
        /etc/nim.cfg(53, 3) Hint: added path: '/root/.babel/pkgs/' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/compiler-0.11.3' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimble-0.6.0' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimsuggest-0.1.0' [Path]
        /etc/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/' [Path]
        Hint: used config file '/etc/nim.cfg' [Conf]
        Error: unhandled exception: cannot open: lib/nim/system/inclrtl.nim [IOError]

**Comment by BitR** [comment]
Some extra debug output:

    root@8751c701d66d:/nim/bin# mv `which nimsuggest` .
    root@8751c701d66d:/nim/bin# ls
    empty.txt  nim  nimsuggest
    root@8751c701d66d:/nim/bin# rm `which nim`
    root@8751c701d66d:/nim/bin# ls
    empty.txt  nim  nimsuggest
    root@8751c701d66d:/nim/bin# ./nim c /test.nim
    config/nim.cfg(53, 3) Hint: added path: '/root/.babel/pkgs/' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/compiler-0.11.3' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimble-0.6.0' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimsuggest-0.1.0' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/' [Path]
    Hint: used config file '/nim/config/nim.cfg' [Conf]
    Hint: system [Processing]
    Hint: test [Processing]
    gcc -c  -w  -I/nim/lib -o nimcache/test.o nimcache/test.c
    gcc -c  -w  -I/nim/lib -o nimcache/stdlib_system.o nimcache/stdlib_system.c
    [Linking]
    Hint: operation successful (9169 lines compiled; 0.666 sec total; 14.143MB; Debug Build) [SuccessX]
    root@8751c701d66d:/nim/bin# ./nimsuggest /test.nim
    config/nim.cfg(53, 3) Hint: added path: '/root/.babel/pkgs/' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/compiler-0.11.3' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimble-0.6.0' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimsuggest-0.1.0' [Path]
    config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/' [Path]
    Hint: used config file '/nim/config/nim.cfg' [Conf]
    Error: unhandled exception: cannot open: lib/system/inclrtl.nim [IOError]

**Comment by pigmej** [comment]
@BitR for now you have to run nimsuggest from location where `lib` exists. So in your case from `/nim`.

That's a temporary bug in nimsuggest.

**Comment by BitR** [comment]
@pigmej: Well, then it seems nimsuggest isn't up to finding my code.

        root@0e2cfc1a92b2:/nim# which nim
        /nim/bin/nim
        root@0e2cfc1a92b2:/nim# which nimsuggest
        /nim/bin/nimsuggest
        root@0e2cfc1a92b2:/nim# nimsuggest --stdin /tmp/test.nim 
        config/nim.cfg(53, 3) Hint: added path: '/root/.babel/pkgs/' [Path]
        config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/compiler-0.11.3' [Path]
        config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimble-0.6.0' [Path]
        config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/nimsuggest-0.1.0' [Path]
        config/nim.cfg(54, 3) Hint: added path: '/root/.nimble/pkgs/' [Path]
        Hint: used config file '/nim/config/nim.cfg' [Conf]
        Error: unhandled exception: cannot open: test.nim [IOError]

Tried removing /root/.nimble afterwards, but I still get the same error.
Moving test.nim to /nim does the trick though.

**Comment by pigmej** [comment]
@BitR  oh so you're having the same issue that I once had.

@BitR Could you please check if relative path works ? If yes, then please check if adding your file to subfolder (like /tmp/blah/test.nim) solves problem.

**Comment by BitR** [comment]
I get the same error when I try
- /tmp/blah/test.nim
- ../tmp/test.nim
- ../tmp/blah/test.nim

**Comment by BitR** [comment]
Just tested the build process using nimble (with [this Dockerfile](https://gist.github.com/BitR/1ab859b62fd79d1c40a4)).
Additionally I tested without using nimble (with [this Dockerfile](https://gist.github.com/BitR/808f46ec11331e008809)).

In both scenarios I got a working nimsuggest binary that could run from either the nimble path or the nim path.

**Comment by dom96** [comment]
Awesome!
