### ISSUE TITLE
UFCS suggests not working on all types

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/nimsuggest#44]
When using some pointer types(in my concrete scenario from the official SDL wrapper), it doesn't suggest procedures after the dot.

Also when I used the parsecfg module it didn't suggest procedures of the Config type, but when I imported tables, it suggested the table member procedures.

I used bleeding edge Nim with Visual Studio Code on Linux

**Comment by Araq** [comment]
A concrete snippet that shows the problem would be nice.

**Comment by RSDuck** [comment]
Yes, of course

```nim
import parsecfg

let cfg = parsecfg.loadConfig("config.ini")
```
When typing cfg. it doesn't suggest the member functions of Config, but when tables is imported...
```nim
import parsecfg, tables

let cfg = parsecfg.loadConfig("config.ini")
```
cfg. suggests the member functions of the underlying OrderedTableRef[string, OrderedTableRef[string, string]]

And here is the second case:
```nim
var x: ptr int

proc foo(y: ptr int) =
    discard
```
When typing x. it doesn't suggest foo, instead it suggests only methods taking an int as the first parameter

EDIT: changed let to var in the last example

**Comment by Araq** [comment]
> When typing cfg. it doesn't suggest the member functions of Config, but when tables is imported...

That's how the language works, not a bug.

**Comment by RSDuck** [comment]
But why does this work(taken from: http://nim-lang.org/docs/parsecfg.html)?
```nim
import parsecfg
var dict = loadConfig("config.ini")
var charset = dict.getSectionValue("","charset")
var threads = dict.getSectionValue("Package","--threads")
var pname = dict.getSectionValue("Package","name")
var name = dict.getSectionValue("Author","name")
var qq = dict.getSectionValue("Author","qq")
var email = dict.getSectionValue("Author","email")
echo pname & "\n" & name & "\n" & qq & "\n" & email
```
EDIT: e.g. when typing dict. it should suggest e.g. getSectionValue, or am I completely wrong?

**Comment by Araq** [comment]
Fixed as far as I can tell.
