### ISSUE TITLE
.member syntax doesn't work when an unrelated symbols follows it

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/nimsuggest#45]
It happends mostly when making procedure calls and VSCode adds the closing bracket by itself:
```nim
someProc(someThing.|)
```
(| is where the cursor is)
It doesn't suggest members the of the object/tuple or the symbols of the package, instead it suggests the symbols in the current scope.

Here is another example:
```nim
if someObject.|:
  discard
```
This bug happends on all statements followed by an body.

EDIT: there is an easy fix for(which is not the right way to fix it, because it messes with other results). I simply modified the VSCode extension that it adds a space after the cursor, before sending the source to nimsuggest and it fixes the bug. 

That works also if it gets done manually so by simply adding a space between the dot and e.g. the bracket.

**Comment by Araq** [comment]
Thanks! That is helpful. :-)

**Comment by RSDuck** [comment]
I forgot to mention that I already found a solution for it, or atleast a hint, why this happends, see the edited orginal post.

**Comment by Araq** [comment]
This has been fixed.
