### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by Krognol** [nim-lang/nimsuggest#49]
After only a few minutes working on a relatively small project nimsuggest is already hogging 4gb of memory. It even went up to 10gb at one point and wouldn't go down unless force quitting the task.
![image](https://cloud.githubusercontent.com/assets/10560012/23007338/6397f048-f408-11e6-8753-0d7832650751.png)

**Comment by Araq** [comment]
Yeah, known issue, we're working on it.

**Comment by Araq** [comment]
The memory usage is now much better.
