### ISSUE TITLE
Regression regarding generic types

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/nimsuggest#52]
Here is an example of what I mean:
```nimrod
import tables, sets, parsecfg

type X = object

var
    set0 = initSet[int]()
    set1 = initSet[X]()
    set2 = initSet[ref int]()

    map0 = initTable[int, int]()
    map1 = initOrderedTable[string, int]()
    cfg = loadConfig("file")

```
When typing `set0.`, `set1.`, `set2.`, `map0` or `map1.` instead of suggestion the member procedures(add, clear, ...), it suggests the variables in the current scope. When typing `cfg.` it suggets all members including the ones "inherited" by OrderedTable as it should.

I'm using bleeding edge Nim from yesterday(https://github.com/nim-lang/Nim/commit/52462f031e6f8605fc3155879c216e25427ca7df)

**Comment by Araq** [comment]
This has been fixed.
