### ISSUE TITLE
Imported symbols aren't shown in certain contexts

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/nimsuggest#54]
mod.nim
```nimrod
proc cube*(x: int): int = x * x * x
```
main.nim
```nimrod
import mod
var x = |
```
In this case `cube` isn't suggested, only local symbols.
There are more cases like this, e.g.:
```nimrod
discard |
```
Also sometimes in the brackets of a procedure call it doesn't work too, but I didn't found a way to reproduce it.

There are probably more cases like these.

**Comment by Araq** [comment]
> In this case cube isn't suggested, only local symbols.

Well cube is not exported.

**Comment by Araq** [comment]
Also this is a feature:

```nim
proc suggestEverything(c: PContext, n, f: PNode, outputs: var Suggestions) =
  # do not produce too many symbols:
  var isLocal = true
  var scopeN = 0
  for scope in walkScopes(c.currentScope):
    if scope == c.topLevelScope: isLocal = false
````

**Comment by RSDuck** [comment]
I forgot the export sign, but anyway the whole issue nonsense(sorry for that). Except one thing. I was able to track down it down:
```nimrod
let x = open("Test", |)
var y = open("Test2", |)
discard open("Test", |)
open("test", |)
```
When the cursor is at position of the first `|` fmRead, fmWrite etc. are suggested(maybe after typing some letters of them, but they are). When the cursor is at the second or third `|` it doesn't no matter how far the symbols are limited. But at the fourthst `|` it does suggests fmRead and fmWrite.

**Comment by Araq** [comment]
I recently reimplemented the cursor tracking in the compiler, so hopefully this will be solved as a side effect.

**Comment by RSDuck** [comment]
This seems to be fixed in the latest git version of Nim
