### ISSUE TITLE
use command returns wrong positions for exported procs

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/nimsuggest#58]
Here is an example of what I mean:
```nim
proc someOtherProc() =
    discard

someOtherProc()

proc someProc*() =
    discard

|someProc()
```
(9:0 is where the | is)
```
> use y.nim:9:0
use     skProc  y.someProc      proc (){.noSideEffect, gcsafe, locks: 0.}       C:\Users\I\Desktop\nimsuggesttest\y.nim     6       13      ""
100
use     skProc  y.someProc      proc (){.noSideEffect, gcsafe, locks: 0.}       C:\Users\I\Desktop\nimsuggesttest\y.nim     9       0       ""
100
```
As you can see in Nimsuggests output the returned column, of the first entry(which is the definiton), is wrong. Instead of the beginning of the identifier it's the end of the identifier. When the export asterix is removed the correct column is returned.

It seems to only effect the `use` command. E.g. the `def` command returns the right result. It doesn't matter whether a reference to the procedure is given as the location the Nimsuggest or the definition.

EDIT: ah, I forgot to mention that I'm using latest Nim devel from today(https://github.com/nim-lang/Nim/commit/e8389dcb93f9f9565e6bfcfdfc2aad32dcc2eb0e).

**Comment by saem** [comment]
Issue was fixed, regression test was added.

Can be closed.
