### ISSUE TITLE
Implement the language server protocol

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimsuggest#59]
http://langserver.org/

**Comment by zah** [comment]
More specifically:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

**Comment by kaushalmodi** [comment]
This will be cool! Work for LSP support has already started for Emacs: https://github.com/emacs-lsp

**Comment by konradbartecki** [comment]
+1

**Comment by PMunch** [comment]
Any progress on this? [Someone](https://irclogs.nim-lang.org/05-02-2018.html#11:28:15) recently asked for this on IRC and it looks like it could solve many of the problems with integration into editors.

**Comment by Araq** [comment]
No progress, sorry. I'll accept PRs but there is no way I'll implement this over-designed protocol.

**Comment by PMunch** [comment]
Oh wow, didn't realise how large that spec was. And it's HTTP/JSON based, why? I can see why you wouldn't want to implement it, but I hope someone can find the time to as it would open a lot of editors for Nim development.

**Comment by dom96** [comment]
This should be implemented in a separate tool that calls to nimsuggest IMO

**Comment by PMunch** [comment]
Now https://github.com/PMunch/nimlsp implements a language protocol server that correctly tracks documents and is able to offer suggestions. It's only a start, but it works, any help appreciated.
