### ISSUE TITLE
DEC64 Number Type?

### ISSUE THREAD

**Issue by cheponis** [nim-lang/nimsuggest#62]
[DEC64 Website](http://dec64.com/) suggests that a single numeric datatype, DEC64, can replace all existing 'integer' types.

DEC64 nicely represents 56-bit ints, and floats/doubles, too.  It could be the ONLY numeric type required.

(With the additional of an 'infinite' integer type such as lisp and python have, as native, would cover the only other (but, still, unusual) case for ints.)

I do think adding the DEC64 type to Nim now (before 1.0) would show everyone that Nim is a very serious contender for a general-purpose programming language for the 21st century.  And, finally, 0.1 + 0.2 would really be equal to 0.3  !!!

**Comment by Araq** [comment]
This is the wrong issue tracker for it. Closing. 

> In modern systems, this sort of memory saving is pointless. 

Ok, that is ridiculous. Memory got slower, not faster.

**Comment by cheponis** [comment]
On Tue, May 9, 2017 at 2:55 AM, Andreas Rumpf <notifications@github.com>
wrote:

> This is the wrong issue tracker for it. Closing.
>
​This is my first post to any nim forum.  I apologize if it's the wrong
issue tracker for it, but: what is the correct issue tracker, then?​



> In modern systems, this sort of memory saving is pointless.
>
> Ok, that is ridiculous. Memory got slower, not faster.
>
​I'm sorry?

I made a proposal to include DEC64 into nim 1.0 for good reasons.  Douglas
Crockford did the DEC64.com website.

Now, it seems that you are saying 'memory' got slower.

I don't think I understand what you are saying?

What memory got slower?

And, how does this invalidate the idea of DEC64?

Thank you,
Mike​

**Comment by Araq** [comment]
Please post it to https://github.com/nim-lang/Nim/issues
