### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/nimsuggest#63]
While nimsuggest generally works great without crashes now, this code generates a crash:

```nim
$ cat t.nim
import random
import hashes
import times
import math
import bitops

template masked(i: untyped): typed {.dirty.}=
  i and m.hi

type
  Entry[K, V] = object
    k: K
    v: V

  Map[K, V] = object
    hv: seq[int]
    data: seq[Entry[K, V]]
    numentries: int

proc insert[K, V](m: var Map[K, V]; key: K; val: V) =
  var i = key.hash
  let p = masked(i)
  i = p
  while 0 < m.hv[masked(i)]:
    inc(i)

proc test() =
  discard

when isMainModule:
  test()
```
$ nim -v
Nim Compiler Version 0.17.0 (2017-05-19) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

$ nim c t.nim
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/stefan/newhood/nim.cfg' [Conf]
Hint: system [Processing]
Hint: t [Processing]
Hint: random [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: hashes [Processing]
Hint: bitops [Processing]
t.nim(20, 6) Hint: 't.insert(m: var Map[insert.K, insert.V], key: K, val: V)' is declared but not used [XDeclaredButNotUsed]
Hint:  [Link]
Hint: operation successful (17067 lines compiled; 0.196 sec total; 28.027MiB peakmem; Debug Build) [SuccessX]

$ nimsuggest --v2 --stdin t.nim
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/stefan/newhood/nim.cfg' [Conf]
usage: sug|con|def|use|dus|chk|mod|highlight|outline|known file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> def t.nim:21:3
Segmentation fault (core dumped)

**Comment by StefanSalewski** [comment]
Well, this more correct code still segfaults:

```nim
import random
import hashes
import times
import math
import bitops

template masked(i: untyped): typed {.dirty.}=
  i and m.hi

type
  Entry[K, V] = object
    k: K
    v: V

  Map[K, V] = object
    hv: seq[int]
    data: seq[Entry[K, V]]
    numentries: int
    hi: int

proc insert[K, V](m: var Map[K, V]; key: K; val: V) =
  var i = key.hash
  let p = masked(i)
  i = p
  while 0 < m.hv[masked(i)]:
    inc(i)

proc test() =
  var m: Map[int, int]
  m.insert(1, 1)
  discard

when isMainModule:
  test()
```
 
nimsuggest --v2 --stdin t.nim
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/stefan/newhood/nim.cfg' [Conf]
usage: sug|con|def|use|dus|chk|mod|highlight|outline|known file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> def t.nim:22:3
Segmentation fault (core dumped)

This modifikation seems to fix it:

```nim
  var i = hash(key)
```

**Comment by narimiran** [comment]
>  Segmentation fault (core dumped)

Both examples work (there is no segfault) with Nim v0.19.9, but nothing is suggested. Is that good enough to be closed?

**Comment by StefanSalewski** [comment]
Seems to work fine now, so I will close it now!
