### ISSUE TITLE
problems with emacs integration

### ISSUE THREAD

**Issue by krux02** [nim-lang/nimsuggest#67]
I don't know if the error is on the side of nimsuggest of on the side of nim-mode, but there is an issue, therefor I link it here: https://github.com/nim-lang/nim-mode/issues/165

**Comment by yuutayamada** [comment]
You might check it by same way as I did:
https://github.com/nim-lang/nimsuggest/issues/37

EDIT:
and just FYI: https://github.com/kiwanami/emacs-epc

**Comment by krux02** [comment]
sorry my bad
