### ISSUE TITLE
`terse` mode crashes nimsuggest

### ISSUE THREAD

**Issue by ghost** [nim-lang/nimsuggest#74]
```
λ nimsuggest --stdin a.nim
Hint: used config file 'E:\Dev\nim\config\nim.cfg' [Conf]
usage: sug|con|def|use|dus|chk|mod|highlight|outline|known file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> terse

> sug

> sug a.nim:1:1
(and crash...)
```

**Comment by nc-x** [comment]
Fails at this line of code - https://github.com/nim-lang/Nim/blob/5f3438a3fe701544e1841419ecac9c8e64d5e66b/nimsuggest/nimsuggest.nim#L460

**Comment by ghost** [comment]
Crashes [here](https://github.com/nim-lang/Nim/blob/d0a9fac36252a135dba6304b9f7ccc18c899c267/compiler/suggest.nim#L171) because `suggest.forth` is `nil`.

**Comment by narimiran** [comment]
Not reproduced. Probably because `suggest.forth`, which is `string`, cannot be `nil` anymore.
