### ISSUE TITLE
nimsuggest SIGSEGV, causing sublimetext plugin to die

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimsuggest#83]
I found the root cause of https://github.com/Varriount/NimLime/issues/99 "error: plugin_host has exited unexpectedly" that causes sublimetext plugin to die often when user makes a type in code; this is bad because we have to restart sublimetext.

Here's a minimal test case:
```nim
#[
# plugin_host bug: https://github.com/Varriount/NimLime/issues/99
open this in sublime text
when use saves this file (eg on OSX: via command + S), the plugin_host will die
seems like a minimal-ish test case: variations of this file won't trigger that bug (eg removing =0, commenting a line, removing {.strdefine.} etc)
]#

const testCase {.strdefine.}: string=0
when false: discard
elif testCase == "test1":
```

nimsuggest bugs/t40_NimLine_plugin_host_crash_1.nim
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by timotheecour** [comment]
can't reproduce anymore... but at the same time NimLime doesn't do anything anymore (which was how I triggered this issue) so I'm not sure I want to close until NimLime does something

**Comment by timotheecour** [comment]
with my PR https://github.com/timotheecour/NimLime/commit/4dca553ebd77410b642b09f4ff5f07c23c476af7 I can finally run NimLime's nim check again, and this particular SIGSEGV doesn't occur on this sample; closing.

**Comment by timotheecour** [comment]
re-opening, the one that's fixed is https://github.com/nim-lang/nimsuggest/issues/84 (which is similar); this one still leads to SIGSEGV

**Comment by alaviss** [comment]
This is more of a compiler bug, you can run `nim check` on that snippet and the compiler will crash. Most nimsuggest bug is a compiler bug imo.

**Comment by timotheecour** [comment]
very possible, will open an issue for nim check; but I want to keep this open until that bug is fixed because it's a common cause of nimsuggest being unusable in some workflows (eg it was disabled bc of that in nimlime for sublimetext)
