### ISSUE TITLE
nimsuggest returns different def depending on column offset within a symbol

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimsuggest#98]
/cc @Araq super weird bug:

nimsuggest returns different def depending on column offset within a symbol
in code below, both col 12 and 13 lie well within `getEnvs2` boundaries, yet produce different results

```nim
#[


]#

import macros

macro echo2(args: untyped): untyped =
  result = newCall(bindSym"echo", args)
  # result = args

proc getEnvs2(): auto =
  result = "asdf"

proc test_getEnvs2()=
  echo2 getEnvs2()


```

nimsuggest --stdin /Users/timothee/git_clone/nim/timn/bugs/nimsuggest/t08.nim
```
BUG:
> def /Users/timothee/git_clone/nim/timn/bugs/nimsuggest/t08.nim:16:12
def     skMacro t08.echo2       proc (args: untyped): untyped{.noSideEffect, gcsafe, locks: 0.} /Users/timothee/git_clone/nim/timn/bugs/nimsuggest/t08.nim      8       6       ""      100

OK:
> def /Users/timothee/git_clone/nim/timn/bugs/nimsuggest/t08.nim:16:13
def     skProc  t08.getEnvs2    proc (): string{.noSideEffect, gcsafe, locks: 0.}       /Users/timothee/git_clone/nim/timn/bugs/nimsuggest/t08.nim      12      5       ""      100

```

Note: a (myabe) related bug is that often `def` doesn't work with macros that take untyped params; this affects for example all code inside a jester route

**Comment by narimiran** [comment]
Tested with the latest Nim v0.19.9, both `... 16:12` and `... 16:13` produce the correct result.
