### ISSUE TITLE
nimsuggest `sug` wrongly reports all symbols on buggy code

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimsuggest#99]
originally reported here: https://github.com/nim-lang/nimsuggest/issues/93#issuecomment-435569720

echo "sug bugs/nimsuggest/t01d.nim:3:6" | $nimc_D/bin/nimsuggest --stdin bugs/nimsuggest/t01d.nim

bugs/nimsuggest/t01d.nim:
```nim
macro mapLiterals(a: untyped): untyped =
  echo a.kind
mapLiterals(0)
```
yes, the above code is buggy (`kind` not defined) but nimsuggest shouldn't return all symbols here

**Comment by nc-x** [comment]
https://github.com/nim-lang/Nim/blob/0409f2348e2ac69a717e4ec7628a99c49fd42f0d/compiler/suggest.nim#L567-L586

```nim
proc suggestSentinel*(c: PContext) =
  if c.config.ideCmd != ideSug or c.module.position != c.config.m.trackPos.fileIndex.int32: return
  if c.compilesContextId > 0: return
  inc(c.compilesContextId)
  var outputs: Suggestions = @[]
  # suggest everything:                          <===============================
  var isLocal = true
  var scopeN = 0
  for scope in walkScopes(c.currentScope):
    if scope == c.topLevelScope: isLocal = false
    dec scopeN
    for it in items(scope.symbols):
      var pm: PrefixMatch
      if filterSymNoOpr(it, nil, pm):
        outputs.add(symToSuggest(c.config, it, isLocal = isLocal, ideSug,
            newLineInfo(c.config.m.trackPos.fileIndex, -1, -1), 0,
            PrefixMatch.None, false, scopeN))

  dec(c.compilesContextId)
produceOutput(outputs, c.config)
```

Seems to be intentional. No idea why though.
cc @Araq

**Comment by narimiran** [comment]
> Seems to be intentional.

So "it is not a bug, it is a feature" :) a.k.a it works as expected.

**Comment by nc-x** [comment]
@narimiran 
  
> "it is not a bug, it is a feature"
  
I am not sure I like this feature (I am not even sure if it is a feature). I mean this `suggestSentinel` should  `suggest everything` if you type a new symbol, but after a dot, if no symbol exists, it shouldn't show anything instead of showing invalid suggestions.
(I don't remember anything about this issue so I don't know if what I just said even makes sense ;) )

**Comment by Araq** [comment]
> Seems to be intentional. No idea why though.

Because a list of options to choose from is better than no list. If I don't want suggestions then why would I invoke nimsuggest?
